version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:v0
  udagramapp_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:v0
  udagramapp_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:v0
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local